### ISSUE TITLE
Create document for project details

### ISSUE THREAD

**Issue by zasdf182** [GhostDaGhost/html-class-final-project#11]
- Lists Team Member names (designate who the PM is)
- Has short summary of the themed topic the web-site supports
- Specifies what team member(s) worked on what parts of the web-site

### Added on 3/4
Address this question in a separate paragraph
Will I need software installed on my machine to run your web application?
If not, then say no software will be needed other than running your web application through the Chrome browser on my machine
If software other than the Chrome browser will be needed
Specify what the software is
Whether an installation will need to be done on my Windows machine
And what the steps and requirements are to install the software

**Comment by CodedByArizola** [comment]
Pretty sure this was done and turned in.

**Comment by zasdf182** [comment]
> Pretty sure this was done and turned in.

For a previous assignment, we turned in a similar document that mainly talked about what was done so far and our plan to finish the rest of the work.

We need to add a description specifying what team members worked on what parts of the website.

And we need to include the document in the .zip file for our final Group Project submission.

See [the Canvas assignment page](https://lwtech.instructure.com/courses/2425603/assignments/31617055)

**Comment by zasdf182** [comment]
Completed document
And I submitted final project on Canvas just to be early
Feel free to make any changes and resubmit if you want to
